### ISSUE TITLE
run-avrdude burns bootloader twice

### ISSUE THREAD

**Issue by will127534** [MediaTek-Labs/linkit-smart-7688-feed#11]
as title,the hex file upload by Arduino IDE already combine the bootloader with code
so don't need to burn bootloader first, also avrdude doesn't clear the chip fist.

So the parameter for avrdude can change to
avrdude -c linuxgpio -C /etc/avrdude.conf -p m32u4 -e -v -Uflash:w:$1 $2

**Comment by blogic** [comment]
please send a documented PR with the appropriate patch
