### ISSUE TITLE
opkg update fails

### ISSUE THREAD

**Issue by versamodule** [MediaTek-Labs/linkit-smart-7688-feed#12]
opkg update fails.
For instance, this is the first line after opkg update.
Downloading http://downloads.openwrt.org/chaos_calmer/15.05/ra...7688/packages/base/Packages.gz

Looking into that folder structure, there is no folder /mt7688 in ramips. Is gone !

**Comment by blogic** [comment]
On 17/02/2016 15:31, Jim wrote:
> opkg update fails.
> For instance, this is the first line after opkg update.
> Downloading
> http://downloads.openwrt.org/chaos_calmer/15.05/ra...7688/packages/base/Packages.gz
> 
> Looking into that folder structure, there is no folder /mt7688 in
> ramips. Is gone !
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12>.
> 


mt7688 was never part of the CC release.

**Comment by versamodule** [comment]
But opkg update, used to work just fine several days ago. Now it does 
not, and its because that folder is gone.


On 2/17/2016 8:36 AM, John Crispin wrote:
>
>
> On 17/02/2016 15:31, Jim wrote:
> > opkg update fails.
> > For instance, this is the first line after opkg update.
> > Downloading
> > 
> http://downloads.openwrt.org/chaos_calmer/15.05/ra...7688/packages/base/Packages.gz
> >
> > Looking into that folder structure, there is no folder /mt7688 in
> > ramips. Is gone !
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12>.
> >
>
>
> mt7688 was never part of the CC release.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185231114>.
>

-- 
Sincerely,

Jimp@Versamodule.com



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by blogic** [comment]
no that folder was never there i upload the folders and mt7688 was never
part of the CC release

you were previously using the feed located on mirror2. however the
mtk-linkit package has changed so that it will work with CC.1


throw these lines into /etc/opk/distfeeds.conf replacing the current content

src/gz chaos_calmer_base http://mirror2.openwrt.org/mt7688_v0.9/base
src/gz chaos_calmer_luci http://mirror2.openwrt.org/mt7688_v0.9/luci
src/gz chaos_calmer_packages http://mirror2.openwrt.org/mt7688_v0.9/packages


-->
https://github.com/MediaTek-Labs/linkit-smart-7688-feed/commit/4c609f606a8637006e6f6137e91b89beed823c84

**Comment by versamodule** [comment]
Thank you I will try that. What is not clear to me is anyone 
downloading  firmware (v0.9.2) will have this same issue.
If things have changed, why is there not a new firmware rev ?





On 2/17/2016 8:45 AM, John Crispin wrote:
> no that folder was never there i upload the folders and mt7688 was never
> part of the CC release
>
> you were previously using the feed located on mirror2. however the
> mtk-linkit package has changed so that it will work with CC.1
>
>
> throw these lines into /etc/opk/distfeeds.conf replacing the current 
> content
>
> src/gz chaos_calmer_base http://mirror2.openwrt.org/mt7688_v0.9/base
> src/gz chaos_calmer_luci http://mirror2.openwrt.org/mt7688_v0.9/luci
> src/gz chaos_calmer_packages 
> http://mirror2.openwrt.org/mt7688_v0.9/packages
>
>
> -->
> https://github.com/MediaTek-Labs/linkit-smart-7688-feed/commit/4c609f606a8637006e6f6137e91b89beed823c84
>
> On 17/02/2016 15:40, Jim wrote:
> > But opkg update, used to work just fine several days ago. Now it does
> > not, and its because that folder is gone.
> >
> >
> > On 2/17/2016 8:36 AM, John Crispin wrote:
> >>
> >>
> >> On 17/02/2016 15:31, Jim wrote:
> >> > opkg update fails.
> >> > For instance, this is the first line after opkg update.
> >> > Downloading
> >> >
> >>
> > 
> http://downloads.openwrt.org/chaos_calmer/15.05/ra...7688/packages/base/Packages.gz
> >> >
> >> > Looking into that folder structure, there is no folder /mt7688 in
> >> > ramips. Is gone !
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12>.
> >> >
> >>
> >>
> >> mt7688 was never part of the CC release.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >>
> > 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185231114>.
> >>
> >
> > --
> > Sincerely,
> >
> > Jimp@Versamodule.com
> >
> >
> >
> > ---
> > This email has been checked for viruses by Avast antivirus software.
> > https://www.avast.com/antivirus
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185233093>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185235194>.
>

-- 
Sincerely,

Jimp@Versamodule.com



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by blogic** [comment]
v0.9.2 points at the folders on mirror2 and works fine.

the reason why 0.9.3 and CC.1 are not public available yet is because
they were not released yet.

the issue you are having is because you built your own image from
source. the binary feed cannot work with your image as they are based on
different git revisions.

the biggest issues will be seen by the kernel as the vermagic of the
binary will be different from your self compiled image compared to the
kmods on mirror2.

**Comment by versamodule** [comment]
Ah... Thanks for the explanation.


On 2/17/2016 9:01 AM, John Crispin wrote:
> v0.9.2 points at the folders on mirror2 and works fine.
>
> the reason why 0.9.3 and CC.1 are not public available yet is because
> they were not released yet.
>
> the issue you are having is because you built your own image from
> source. the binary feed cannot work with your image as they are based on
> different git revisions.
>
> the biggest issues will be seen by the kernel as the vermagic of the
> binary will be different from your self compiled image compared to the
> kmods on mirror2.
>
>
>
> On 17/02/2016 15:51, Jim wrote:
> > Thank you I will try that. What is not clear to me is anyone
> > downloading firmware (v0.9.2) will have this same issue.
> > If things have changed, why is there not a new firmware rev ?
> >
> >
> >
> >
> >
> > On 2/17/2016 8:45 AM, John Crispin wrote:
> >> no that folder was never there i upload the folders and mt7688 was 
> never
> >> part of the CC release
> >>
> >> you were previously using the feed located on mirror2. however the
> >> mtk-linkit package has changed so that it will work with CC.1
> >>
> >>
> >> throw these lines into /etc/opk/distfeeds.conf replacing the current
> >> content
> >>
> >> src/gz chaos_calmer_base http://mirror2.openwrt.org/mt7688_v0.9/base
> >> src/gz chaos_calmer_luci http://mirror2.openwrt.org/mt7688_v0.9/luci
> >> src/gz chaos_calmer_packages
> >> http://mirror2.openwrt.org/mt7688_v0.9/packages
> >>
> >>
> >> -->
> >>
> > 
> https://github.com/MediaTek-Labs/linkit-smart-7688-feed/commit/4c609f606a8637006e6f6137e91b89beed823c84
> >>
> >> On 17/02/2016 15:40, Jim wrote:
> >> > But opkg update, used to work just fine several days ago. Now it does
> >> > not, and its because that folder is gone.
> >> >
> >> >
> >> > On 2/17/2016 8:36 AM, John Crispin wrote:
> >> >>
> >> >>
> >> >> On 17/02/2016 15:31, Jim wrote:
> >> >> > opkg update fails.
> >> >> > For instance, this is the first line after opkg update.
> >> >> > Downloading
> >> >> >
> >> >>
> >> >
> >>
> > 
> http://downloads.openwrt.org/chaos_calmer/15.05/ra...7688/packages/base/Packages.gz
> >> >> >
> >> >> > Looking into that folder structure, there is no folder /mt7688 in
> >> >> > ramips. Is gone !
> >> >> >
> >> >> > —
> >> >> > Reply to this email directly or view it on GitHub
> >> >> > 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12>.
> >> >> >
> >> >>
> >> >>
> >> >> mt7688 was never part of the CC release.
> >> >>
> >> >> —
> >> >> Reply to this email directly or view it on GitHub
> >> >>
> >> >
> >>
> > 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185231114>.
> >> >>
> >> >
> >> > --
> >> > Sincerely,
> >> >
> >> > Jimp@Versamodule.com
> >> >
> >> >
> >> >
> >> > ---
> >> > This email has been checked for viruses by Avast antivirus software.
> >> > https://www.avast.com/antivirus
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> >
> >>
> > 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185233093>.
> >> >
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >>
> > 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185235194>.
> >>
> >
> > --
> > Sincerely,
> >
> > Jimp@Versamodule.com
> >
> >
> >
> > ---
> > This email has been checked for viruses by Avast antivirus software.
> > https://www.avast.com/antivirus
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185237291>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/12#issuecomment-185242264>.
>

-- 
Sincerely,

Jimp@Versamodule.com



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by DumiduNadeera** [comment]
Hi ,
I'm having the same issue.
these are the 1st few line that i'm getting

opkg update failed.
Downloading http://mirror2.openwrt.org/mt7688_v0.9/base/Packages.gz.
wget: bad address 'mirror2.openwrt.org'
Downloading http://mirror2.openwrt.org/mt7688_v0.9/base/Packages.sig.
wget: bad address 'mirror2.openwrt.org'
Signature check failed.
Remove wrong Signature file.
