### ISSUE TITLE
Compile OpenWRT from source failed

### ISSUE THREAD

**Issue by bapclenet** [MediaTek-Labs/linkit-smart-7688-feed#14]
Hi,

I download OpenWRT, last build, I fed the package as explained in the README and selected the target in manuconfig, and then compile, I finally get an error :
```
cp -fpR trunk/build_dir/target-mipsel_24kec+dsp_musl-1.1.12/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ap_client /trunk/build_dir/target-mipsel_24kec+dsp_musl-1.1.12/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/sbin/
cp -fpR ./wifi_binary/mt_wifi.ko_4.3.4 trunk/build_dir/target-mipsel_24kec+dsp_musl-1.1.12/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/lib/modules/4.3.4/mt_wifi.ko
cp: cannot stat './wifi_binary/mt_wifi.ko_4.3.4': No such file or directory
make[3]: *** [trunk-linux4.3/trunk/bin/ramips/packages/linkit/mtk-sdk-wifi_2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371_ramips_24kec.ipk] Error 1
make[3]: Leaving directory `trunk/feeds/linkit/mtk-sdk-wifi'
make[2]: *** [package/feeds/linkit/mtk-sdk-wifi/compile] Error 2
```

Why mt_wifi.ko_4.3.4 is not created?

**Comment by blogic** [comment]
On 18/02/2016 19:35, bapclenet wrote:
> Hi,
> 
> I download OpenWRT, last build, I fed the package as explained in the
> README and selected the target in manuconfig, and then compile, I
> finally get an error :
> 
> |cp -fpR
> trunk/build_dir/target-mipsel_24kec+dsp_musl-1.1.12/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ap_client
> /trunk/build_dir/target-mipsel_24kec+dsp_musl-1.1.12/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/sbin/
> cp -fpR ./wifi_binary/mt_wifi.ko_4.3.4
> trunk/build_dir/target-mipsel_24kec+dsp_musl-1.1.12/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/lib/modules/4.3.4/mt_wifi.ko
> cp: cannot stat './wifi_binary/mt_wifi.ko_4.3.4': No such file or
> directory make[3]: ***
> [trunk-linux4.3/trunk/bin/ramips/packages/linkit/mtk-sdk-wifi_2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371_ramips_24kec.ipk]
> Error 1 make[3]: Leaving directory `trunk/feeds/linkit/mtk-sdk-wifi'
> make[2]: *** [package/feeds/linkit/mtk-sdk-wifi/compile] Error 2 |
> 
> Why mt_wifi.ko_4.3.4 is not created?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/14>.
> 

this board uses a propitiatory closed source wifi driver that is not
opensource. currently only CC release is supported with the 3.18 kernel.
it is currently not possible to build trunk images for this hardware
with wifi support.

**Comment by bapclenet** [comment]
I partially understand.
How did they lock the wifi driver to only work with kernel 3.18?
Linkit works with Kernel 4.3 so why the wifi driver doesn't work with 4.3?
I don't get it, they wrote a README [1] which we can follow to build OpenWRT and add their package (they have been downloaded in my repo so I've got the source if I don't make a mistake "mtk-sdk-wifi-2015-06-01") and I can't compile it then?

[Link 1] (https://github.com/MediaTek-Labs/linkit-smart-7688-feed/blob/master/README.md)

**Comment by blogic** [comment]
On 18/02/2016 19:53, bapclenet wrote:
> I partially understand.
> How did they lock the wifi driver to only work with kernel 3.18?

the binary driver and the kernel both have a so called version magic.
this is a generic linux feature. with every kernel change the binary
wont work anymore as the internal API of the kernel might have changed.
this has nothing to do with the linkit smart but is a generic linux
"feature". there is no lock down in place at all and there wont ever be one.

> Linkit works with Kernel 4.3 so why the wifi driver doesn't work with 4.3?
> I don't get it, they wrote a README [1] which we can follow to build

ok, i think i understand, you did not check out chaos calmer but trunk
for some reason.

you probably called

$ git clone git://git.openwrt.org/openwrt.git

instead of

$ git clone git://git.openwrt.org/15.05/openwrt.git

> OpenWRT and add their package (they have been downloaded in my repo so
> I've got the source if I don't make a mistake "mtk-sdk-wifi-2015-06-01")
> and I can't compile it then?

that wont work, because the driver needs patches to work with openwrt.
this whole problem will be gone real soon as we are working on a
opensource wifi driver based on mac80211. its called mt76 and the
sources are already available on github. but it is not complete yet and
still requires some work.

what i will do is also build a binary for the current kernel in trunk to
make sure that you can build a functional image. however i must note
that to get all features of the lks running you should switch to the
15.05 branch as all features are thoroughly tested in that tree.

**Comment by bapclenet** [comment]
Ok I do better understand now. 
Indeed, I did a clone of the current trunk, add the package to the feed and try to compile.

Yes of course, any change to the kernel may alter the behaviour of a software. 
As soon as I saw that linkit was ported to kernel 4.3 on OpenWRT, I thought that I would have been able to use the wifi driver they provide on this repo.

Anyway, that's a very good news to hear that you're working on an open source wifi driver ! 
I wonder how you do to develop it since mediatek datasheet are not well-detailed and there is nothing concerning wifi on mt7628 datasheet. How do you do and when do you think it will be released ?

**Comment by bapclenet** [comment]
I will close this issue after your answer
Thanks again

**Comment by bapclenet** [comment]
@blogic?

**Comment by changyuheng** [comment]
Do you release the Wi-Fi source yet?

**Comment by blogic** [comment]
yes ?

**Comment by bapclenet** [comment]
Someone asked on the mailing list:
Chang Yu-heng
Do you release the Wi-Fi source yet?
So yes he did: https://github.com/openwrt/mt76

I still wonder how you develop it since mediatek datasheet are not well-detailed and there is nothing concerning wifi on mt7628 datasheet?

**Comment by engkan2kit** [comment]
I just followed this https://github.com/MediaTek-Labs/linkit-smart-7688-feed but then the mt_wifi.ko_3.18.29 error is there? I thought based on the above comments, that if I used the 15.05 branch, it will work.

**Comment by engkan2kit** [comment]
Oh sorry, the kernel was update to 3.18.29 two days ago.

**Comment by blogic** [comment]
On 02/04/2016 15:50, engkan2kit wrote:
> Oh sorry, the kernel was update to 3.18.29 two days ago.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/14#issuecomment-204719871>
> 

i'll push a new wifi binary on monday

**Comment by engkan2kit** [comment]
I'm using the previous commit for now. Thank you.
