### ISSUE TITLE
issues booting with the ftdi connection 

### ISSUE THREAD

**Issue by contractorwolf** [MediaTek-Labs/linkit-smart-7688-feed#16]
I just got the 7688 Dou and am excited to try it out.  I dont know hwat the issue is.  When I power it over the USB cable it turns the greeen LED on then the Orange LED on, but the Orange LED never turns off.  I connected using you recommendations here:
http://www.seeedstudio.com/wiki/LinkIt_Smart_7688_Duo

but mine orange LED never turns off, so I connected with an FTDI Basic and watched it boot.  Seems fine, until the board gets to this part of the boot process: 

[    4.780000] sdhci-pltfm: SDHCI platform and OF driver helper
[    4.790000] usbcore: registered new interface driver usb-storage
[    4.810000] platform gpio-leds: Driver leds-gpio requests probe deferral
[    5.180000] init: - preinit -
[    6.210000] rt305x-esw 10110000.esw: link changed 0x00
[    6.410000] random: mktemp urandom read with 9 bits of entropy available
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
1
[    7.620000] jffs2: notice: (368) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[    7.670000] mount_root: switching to jffs2 overlay
[    7.700000] procd: - early -
[    7.710000] procd: - watchdog -
[    8.510000] procd: - ubus -
[    9.530000] procd: - init -
Please press Enter to activate this console.
Failed to executPlease press Enter to activate this console. <--HERE is where it bombs out, it will stick here and then respond to any further messages with 
"Failed to executPlease press Enter to activate this console"

I dont know what to try next, seems to be failing to boot into the OS, but it is a brand new board just out of the box. Any guesses?

**Comment by blogic** [comment]
On 06/03/2016 05:26, james wolf wrote:
> I just got the 7688 Dou and am excited to try it out. I dont know hwat
> the issue is. When I power it over the USB cable it turns the greeen LED
> on then the Orange LED on, but the Orange LED never turns off. I
> connected using you recommendations here:
> http://www.seeedstudio.com/wiki/LinkIt_Smart_7688_Duo
> 
> but mine orange LED never turns off, so I connected with an FTDI Basic
> and watched it boot. Seems fine, until the board gets to this part of
> the boot process:
> |
> [ 4.780000] sdhci-pltfm: SDHCI platform and OF driver helper
> [ 4.790000] usbcore: registered new interface driver usb-storage
> [ 4.810000] platform gpio-leds: Driver leds-gpio requests probe deferral
> [ 5.180000] init: - preinit -
> [ 6.210000] rt305x-esw 10110000.esw: link changed 0x00
> [ 6.410000] random: mktemp urandom read with 9 bits of entropy available
> Press the [f] key and hit [enter] to enter failsafe mode
> Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
> 1
> [ 7.620000] jffs2: notice: (368) jffs2_build_xattr_subsystem: complete
> building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of
> xref (0 dead, 0 orphan) found.
> [ 7.670000] mount_root: switching to jffs2 overlay
> [ 7.700000] procd: - early -
> [ 7.710000] procd: - watchdog -
> [ 8.510000] procd: - ubus -
> [ 9.530000] procd: - init -
> Please press Enter to activate this console.
> Failed to executPlease press Enter to activate this console.
> |
> <--here is where it bombs out, it will stick here and then respond to
> any further messages with
> "Failed to executPlease press Enter to activate this console"
> 
> I dont know what to try next, seems to be failing to boot into the OS,
> but it is a brand new board just out of the box. Any guesses?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/16>.
> 


looks like the OS is not properly flashed onto the board. you can try to
recover it using the uboot recovery method.

**Comment by contractorwolf** [comment]
ok, got any details on how to do that?

**Comment by blogic** [comment]
On 06/03/2016 08:31, james wolf wrote:
> ok, got any details on how to do that?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/16#issuecomment-192820336>.
> 

page 46 of the developers guide

"You now have the latest firmware on your LinkIt Smart 7688 development
board.
• Using a USB drive :"

.....

**Comment by blogic** [comment]
On 06/03/2016 08:31, james wolf wrote:
> ok, got any details on how to do that?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/16#issuecomment-192820336>.
> 

if that does not work, file a RMA request and have them send you a free
replacement board. you payed top dollar so you should really get a
functional board delivered. not sure how such a board passed QA.

**Comment by xhdix** [comment]
**4.5.4.2. Using Serial to USB Cable** 

After:
`[    6.480000] random: mktemp urandom read with 10 bits of entropy available
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
`

Press the [**f**] key and hit [**enter**]

Then write: 
`# firstboot -y
`
You see : 
`[   99.410000] jffs2reset: /dev/mtdblock6 is not mounted
[   99.420000] jffs2reset: /dev/mtdblock6 will be erased on next mount
`

Then write:
`# reboot
`
And you see:
 ` [  112.630000] reboot: Restarting system
`

**This method worked for me.**

But why did such a problem occur?
No change was made before this problem.

Even through MicroSD I couldn't upgrade the firmware.

**Comment by stone-tong** [comment]
Hello everyone,

Hardware platform: MTK7688a
OS: OpenWrt 18.04 stable
I also ran into this problem.

The followings is my phenomenon.
After I flashed my FW into flash, the device can boot up. But after using many times(not sure the times), power up the device and will appear these messages "Failed to executPlease press Enter to activate this console"
Can anyone give me some advice to solve this?
Thanks.

**Comment by imnotwannafire** [comment]
> wings is my phenomenon.
> After I flashed my FW into flash, the device can boot up. But after using many times(not sure the times), power up the device and will appear these messages "Failed to executPlease press Enter to activate this console"
> Can anyone give me some advice to solve this?

I'm having the same problem as you.
Do you know the root cause of it.
