### ISSUE TITLE
About mt_wifi.ko_3.18.27 No such file or directory

### ISSUE THREAD

**Issue by oldzou** [MediaTek-Labs/linkit-smart-7688-feed#17]
hi:
I try Compile OpenWRT  mt7688 fireware by MediaTek_LinkIt_Smart_7688_Developers_Guide_V1.1.pdf 7.1;

cp -fpR /home/jasonz/work/mt7688/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ap_client /home/jasonz/work/mt7688/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/sbin/
cp -fpR ./wifi_binary/mt_wifi.ko_3.18.27 /home/jasonz/work/mt7688/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/lib/modules/3.18.27/mt_wifi.ko
cp: cannot stat './wifi_binary/mt_wifi.ko_3.18.27': No such file or directory
make[3]: *** [/home/jasonz/work/mt7688/openwrt/bin/ramips/packages/linkit/mtk-sdk-wifi_2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371_ramips_24kec.ipk] Error 1
make[3]: Leaving directory `/home/jasonz/work/mt7688/openwrt/feeds/linkit/mtk-sdk-wifi'
make[2]: *** [package/feeds/linkit/mtk-sdk-wifi/compile] Error 2
make[2]: Leaving directory `/home/jasonz/work/mt7688/openwrt'
make[1]: *** [/home/jasonz/work/mt7688/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/jasonz/work/mt7688/openwrt'
make: *** [world] Error 2

How to solve it ?

**Comment by versamodule** [comment]
Getting the same results

**Comment by blogic** [comment]
On 06/03/2016 06:15, Jim wrote:
> Getting the same results

they joy of proprietary closed source wifi ... i will build yet another
binary today ...

**Comment by darach** [comment]
Ditto. Broken.

**Comment by blogic** [comment]
On 07/03/2016 20:09, Darach Ennis wrote:
> Ditto. Broken.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/17#issuecomment-193400337>.
> 

i accidentally fragged my build tree. it is building just now. i hope to
have the binary ready before i go to bed. sorry for the delay.

**Comment by darach** [comment]
@blogic Thanks for the update!

**Comment by blogic** [comment]
On 07/03/2016 21:01, Darach Ennis wrote:
> @blogic <https://github.com/blogic> Thanks for the update!
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/17#issuecomment-193425130>.
> 


try now please, i just pushed he kernel module for v3.8.27

**Comment by darach** [comment]
@blogic Did the trick. Build continues now from that point. :+1:

**Comment by widora** [comment]
Thanks for the update!

**Comment by blogic** [comment]
On 07/03/2016 21:19, mango wrote:
> Thanks for the update!
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/17#issuecomment-193432483>.
> 

i have started testing the new GPL licensed mac80211 based driver. i am
hoping that testing continues to go well so that we can have the choice
in the near future. i think the official releases will continue to be
based on the closed SDK driver, but for people choosing to build their
own images, using the mac80211 has many benefits.

**Comment by versamodule** [comment]
Did any of you guys make it to the end of the compile yet ? 
Mine is getting stuck here now. 

mkdir -p /home/jim/openwrt/dl
/home/jim/openwrt/scripts/download.pl "/home/jim/openwrt/dl" "openssl-1.0.2g.tar.gz" "f3c710c045cdee5fd114feb69feba7aa" "" "http://www.openssl.org/source/" "http://www.openssl.org/source/old/1.0.2/" "ftp://ftp.funet.fi/pub/crypt/mirrors/ftp.openssl.org/source" "ftp://ftp.sunet.se/pub/security/tools/net/openssl/source/"
--2016-03-07 12:35:50--  http://www.openssl.org/source/openssl-1.0.2g.tar.gz
Resolving www.openssl.org (www.openssl.org)... 194.97.150.234, 2001:608:c00:180::1:ea
Connecting to www.openssl.org (www.openssl.org)|194.97.150.234|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

**Comment by darach** [comment]
@versamodule Getting stuck at the same point.

**Comment by darach** [comment]
A tweak to the build fixes:

```
git diff package/libs/openssl/Makefile
diff --git a/package/libs/openssl/Makefile b/package/libs/openssl/Makefile
index 0b96557..57dd6dc 100644
--- a/package/libs/openssl/Makefile
+++ b/package/libs/openssl/Makefile
@@ -18,6 +18,7 @@ PKG_BUILD_PARALLEL:=1

 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
 PKG_SOURCE_URL:=http://www.openssl.org/source/ \
+        https://www.openssl.org/source/ \
        http://www.openssl.org/source/old/$(PKG_BASE)/ \
        ftp://ftp.funet.fi/pub/crypt/mirrors/ftp.openssl.org/source \
        ftp://ftp.sunet.se/pub/security/tools/net/openssl/source/
```

**Comment by widora** [comment]
@blogic 
God hard, pay attention to the body, I also want to use mac8011 instead of official closed source drivers, more suitable for open source hardware with that MT7688 will estimated when the time comes, more people will choose to mac80211.

**Comment by akent** [comment]
Hi @blogic - upstream OpenWRT have updated the kernel version yet again to from 3.18.27 to 3.18.29. Any chance of yet another kernel module build?

Perhaps more importantly -- what news of the open source WiFi driver? Is it available somewhere, even in some prerelease form?

**Comment by blogic** [comment]
On 04/04/2016 06:01, Adam Kent wrote:
> Hi @blogic <https://github.com/blogic> - upstream OpenWRT have updated
> the kernel version yet again to from 3.18.27 to 3.18.29. Any chance of
> yet another kernel module build?

will do today

> 
> Perhaps more importantly -- what news of the open source WiFi driver? Is
> it available somewhere, even in some prerelease form?
> 

it is already part of trunk and will probably be backported to CC. the
developer handling the driver is currently on vacation.

**Comment by akent** [comment]
Ah I see, that's great news, I'll take a look at trunk! Thanks.

**Comment by blogic** [comment]
add the 3.18.29 binaries.

**Comment by garylijs** [comment]
@blogic Hi, if there's any update about the new kernel(3.18.44). I also met the same issue as below:
About mt_wifi.ko_3.18.44 No such file or directory

**Comment by guanch1984** [comment]
@blogic @garylijs same here, 
cp: cannot stat './wifi_binary/mt_wifi.ko_3.18.44': No such file or directory

**Comment by mllevitin** [comment]
Yes, using .44 $(LINUX_VERSION) during build getting 
p: cannot stat './wifi_binary/mt_wifi.ko_3.18.44': No such file or directory

**Comment by brownx** [comment]
Same with newer version: cp -fpR ./wifi_binary/mt_wifi.ko_3.18.45
not found and neither here on GIT

**Comment by waynepiekarski** [comment]
I have the same problem with: cannot stat './wifi_binary/mt_wifi.ko_3.18.45': No such file or directory

**Comment by nelsonchung** [comment]
I have the same problem now

====================================================
cp: cannot stat './wifi_binary/mt_wifi.ko_3.18.45': No such file or directory
make[3]: *** [openwrt/bin/ramips/packages/linkit/mtk-sdk-wifi_2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371_ramips_24kec.ipk] Error 1
====================================================

and I try previous solution and not work now.

==========================================================
diff --git a/package/libs/openssl/Makefile b/package/libs/openssl/Makefile
index ea68f16..38120f9 100644
--- a/package/libs/openssl/Makefile
+++ b/package/libs/openssl/Makefile
@@ -18,6 +18,7 @@ PKG_BUILD_PARALLEL:=1
 
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
 PKG_SOURCE_URL:=http://www.openssl.org/source/ \
+    https://www.openssl.org/source/ \
        http://www.openssl.org/source/old/$(PKG_BASE)/ \
        ftp://ftp.funet.fi/pub/crypt/mirrors/ftp.openssl.org/source \
        ftp://ftp.sunet.se/pub/security/tools/net/openssl/source/
===========================================================

**Comment by blogic** [comment]
please contact "VincentSH Hsu (徐士璿) <vincentsh.hsu@mediatek.com>"

**Comment by kopanitsa** [comment]
This is *dirty* workaround but it looks to work for AP mode and STA mode.

```
cd <openwrt_SDK_root>/feeds/linkit/mtk-sdk-wifi/wifi_binary
cp mt_wifi.ko_3.18.44 mt_wifi.ko_3.18.45
cp mt_wifi.ko_3.18.44_all mt_wifi.ko_3.18.45_all
```
