### ISSUE TITLE
support for musl instead of uclib

### ISSUE THREAD

**Issue by nites** [MediaTek-Labs/linkit-smart-7688-feed#18]
-std=c++11 is not working on uclib. will musl be supported in future builds of the firmware? I tried compiling trunk for the 7688 but it creates more problems than solutions. I could replace replace the c++11 functions with a more uclibc friendly ones but it's a bit counter intuitive to use an old library on a new system we are trying to develop.
Please advise.

sample error:

> main.cpp:15:22: error: 'stoi' is not a member of 'std'

**Comment by blogic** [comment]
On 02/04/2016 10:32, Omar Lim wrote:
> -std=c++11 is not working on uclib. will musl be supported in future
> builds of the firmware? I tried compiling trunk for the 7688 but it
> creates more problems than solutions. I could replace replace the c++11
> functions with a more uclibc friendly ones but it's a bit counter
> intuitive to use an old library on a new system we are trying to develop.
> Please advise.
> 
> sample error:
> 
>     main.cpp:15:22: error: 'stoi' is not a member of 'std'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/18>
> 

which package is this ?

try including include/uclibc++.mk and setting CONFIG_USE_LIBSTDCXX

that might work.
