### ISSUE TITLE
wireless driver bug

### ISSUE THREAD

**Issue by skyatua** [MediaTek-Labs/linkit-smart-7688-feed#20]
Hi. I buiid openwrt image from sources and after upgrading system have next log in console:
Starting kernel ...

[    0.000000] Linux version 3.18.29 (sky@linx) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r49177) ) #3 Mon Apr 18 13:57:31 EEST 2016
[    0.000000] Board has DDR2
[    0.000000] Analog PMU set to hw control
[    0.000000] Digital PMU set to hw control
[    0.000000] SoC Type: MediaTek MT7688 ver:1 eco:2
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019655 (MIPS 24KEc)
[    0.000000] MIPS: machine is MediaTek LinkIt Smart 7688
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x07ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x07ffffff]
[    0.000000] Initmem setup node 0 [mem 0x00000000-0x07ffffff]
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32512
[    0.000000] Kernel command line: console=ttyS2,57600 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=00040000
[    0.000000] Readback ErrCtl register=00040000
[    0.000000] Memory: 126272K/131072K available (2553K kernel code, 126K rwdata, 524K rodata, 180K init, 186K bss, 4800K reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:256
[    0.000000] intc: using register map from devicetree
[    0.000000] CPU Clock: 580MHz
[    0.000000] clocksource_of_init: no matching clocksources found
[    0.000000] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.060000] pid_max: default: 32768 minimum: 301
[    0.060000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.070000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.080000] pinctrl core: initialized pinctrl subsystem
[    0.090000] NET: Registered protocol family 16
[    0.110000] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.120000] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.130000] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.140000] Switched to clocksource MIPS
[    0.150000] NET: Registered protocol family 2
[    0.150000] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.170000] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.180000] TCP: Hash tables configured (established 1024 bind 1024)
[    0.190000] TCP: reno registered
[    0.200000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.210000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.220000] NET: Registered protocol family 1
[    0.230000] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.250000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.260000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.290000] msgmni has been set to 246
[    0.300000] io scheduler noop registered
[    0.310000] io scheduler deadline registered (default)
[    0.320000] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    0.340000] 10000c00.uartlite: ttyS0 at MMIO 0x10000c00 (irq = 28, base_baud = 2500000) is a 16550A
[    0.350000] 10000d00.uart1: ttyS1 at MMIO 0x10000d00 (irq = 29, base_baud = 2500000) is a 16550A
[    0.370000] console [ttyS2] disabled
[    0.380000] 10000e00.uart2: ttyS2 at MMIO 0x10000e00 (irq = 30, base_baud = 2500000) is a 16550A
[    0.400000] console [ttyS2] enabled
[    0.400000] console [ttyS2] enabled
[    0.410000] bootconsole [early0] disabled
[    0.410000] bootconsole [early0] disabled
[    0.430000] spi-mt7621 10000b00.spi: sys_freq: 193333333
[    0.440000] m25p80 spi32766.0: mx25l25635e (32768 Kbytes)
[    0.450000] m25p80 spi32766.0: using chunked io
[    0.460000] 4 ofpart partitions found on MTD device spi32766.0
[    0.470000] Creating 4 MTD partitions on "spi32766.0":
[    0.480000] 0x000000000000-0x000000030000 : "u-boot"
[    0.500000] 0x000000030000-0x000000040000 : "u-boot-env"
[    0.510000] 0x000000040000-0x000000050000 : "factory"
[    0.520000] 0x000000050000-0x000002000000 : "firmware"
[    0.590000] 2 uimage-fw partitions found on MTD device firmware
[    0.600000] 0x000000050000-0x000000169cec : "kernel"
[    0.610000] 0x000000169cec-0x000002000000 : "rootfs"
[    0.620000] mtd: device 5 (rootfs) set to be root filesystem
[    0.630000] 1 squashfs-split partitions found on MTD device rootfs
[    0.650000] 0x0000016b0000-0x000002000000 : "rootfs_data"
[    0.670000] ralink_soc_eth 10100000.ethernet eth0: ralink at 0xb0100000, irq 5
[    0.690000] mt7621_wdt 10000120.watchdog: Initialized
[    0.700000] TCP: cubic registered
[    0.710000] NET: Registered protocol family 17
[    0.720000] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
[    0.740000] 8021q: 802.1Q VLAN Support v1.8
[    0.750000] mtk-linkit bootstrap: Version  : LINKITS7688
[    0.760000] mtk-linkit bootstrap: Revision : REV3
[    0.770000] mtk-linkit bootstrap: setting up bootstrap latch
[    0.790000] VFS: Mounted root (squashfs filesystem) readonly on device 31:5.
[    0.800000] Freeing unused kernel memory: 180K (80323000 - 80350000)
[    2.350000] init: Console is alive
[    2.360000] init: - watchdog -
[    4.360000] usbcore: registered new interface driver usbfs
[    4.370000] usbcore: registered new interface driver hub
[    4.380000] usbcore: registered new device driver usb
[    4.400000] exFAT: Version 1.2.9
[    4.410000] SCSI subsystem initialized
[    4.430000] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.440000] ehci-platform: EHCI generic platform driver
[    4.460000] phy phy-10120000.usbphy.0: remote usb device wakeup disabled
[    4.470000] phy phy-10120000.usbphy.0: UTMI 16bit 30MHz
[    4.490000] ehci-platform 101c0000.ehci: EHCI Host Controller
[    4.500000] ehci-platform 101c0000.ehci: new USB bus registered, assigned bus number 1
[    4.510000] ehci-platform 101c0000.ehci: irq 26, io mem 0x101c0000
[    4.540000] ehci-platform 101c0000.ehci: USB 2.0 started, EHCI 1.00
[    4.550000] hub 1-0:1.0: USB hub found
[    4.560000] hub 1-0:1.0: 1 port detected
[    4.570000] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.580000] ohci-platform: OHCI generic platform driver
[    4.590000] ohci-platform 101c1000.ohci: Generic Platform OHCI controller
[    4.610000] ohci-platform 101c1000.ohci: new USB bus registered, assigned bus number 2
[    4.620000] ohci-platform 101c1000.ohci: irq 26, io mem 0x101c1000
[    4.690000] hub 2-0:1.0: USB hub found
[    4.700000] hub 2-0:1.0: 1 port detected
[    4.710000] platform gpio-leds: Driver leds-gpio requests probe deferral
[    4.730000] MTK MSDC device init.
[    4.780000] mtk-sd: MediaTek MT6575 MSDC Driver
[    4.790000] sdhci: Secure Digital Host Controller Interface driver
[    4.800000] sdhci: Copyright(c) Pierre Ossman
[    4.810000] platform gpio-leds: Driver leds-gpio requests probe deferral
[    4.830000] sdhci-pltfm: SDHCI platform and OF driver helper
[    4.840000] usbcore: registered new interface driver usb-storage
[    4.880000] mmc0: new high speed SDHC card at address 0007
[    4.900000] mmcblk0: mmc0:0007 SD16G 14.4 GiB
[    4.910000]  mmcblk0: p1
[    4.910000] platform gpio-leds: Driver leds-gpio requests probe deferral
[    5.390000] init: - preinit -
[    6.250000] rt305x-esw 10110000.esw: link changed 0x00
[    6.420000] random: procd urandom read with 10 bits of entropy available
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[    9.730000] mount_root: jffs2 not ready yet, using temporary tmpfs overlay
[    9.760000] procd: - early -
[    9.770000] procd: - watchdog -
[   10.640000] procd: - ubus -
Command failed: Not found
Command failed: Not found
[   11.660000] procd: - init -
Please press Enter to activate this console.
[   13.790000] NET: Registered protocol family 10
[   13.870000] tun: Universal TUN/TAP device driver, 1.6
[   13.880000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[   13.900000] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   13.920000] i2c /dev entries driver
[   14.660000]
[   14.660000]
[   14.660000] === pAd = c0507000, size = 1465992 ===
[   14.660000]
[   14.680000] <-- RTMPAllocTxRxRingMemory, Status=0, ErrorValue=0x
[   14.690000] <-- RTMPAllocAdapterBlock, Status=0
[   14.700000] RtmpChipOpsHook(492): Not support for HIF_MT yet!
[   14.720000] mt7628_init()-->
[   14.720000] mt7628_init(FW(8a00), HW(8a01), CHIPID(7628))
[   14.730000] e2.bin mt7628_init(1117)::(2), pChipCap->fw_len(63056)
[   14.740000] mt_bcn_buf_init(218): Not support for HIF_MT yet!
[   14.760000] <--mt7628_init()
[   14.760000] mtk_gpio_wifi gpio-wifi: registering 1 gpio
[   14.810000] i2c-ralink 10000900.i2c: loaded
[   14.830000] Linux video capture interface: v2.00
[   14.880000] Enable Ralink GDMA Controller Module
[   14.890000] GDMA IP Version=3
[   14.910000] ******* mt76xx_pcm_init *******
[   14.920000] *******Enter codec_wm8960_i2c_probe********
[   14.930000] soc-audio soc-audio: ASoC: machine MTK APSoC I2S should use snd_soc_register_card()
[   14.950000] wm8960 0-001a: No platform data supplied
[   14.960000] soc-audio soc-audio: wm8960-hifi <-> mt76xx-i2s mapping ok
[   14.980000] ip_tables: (C) 2000-2006 Netfilter Core Team
[   15.010000] nf_conntrack version 0.5.0 (1975 buckets, 7900 max)
[   15.060000] Netfilter messages via NETLINK v0.30.
[   15.100000] usbcore: registered new interface driver usbserial
[   15.120000] usbcore: registered new interface driver usbserial_generic
[   15.130000] usbserial: USB Serial support registered for generic
[   15.150000] usbcore: registered new interface driver uvcvideo
[   15.160000] USB Video Class driver (1.1.1)
[   15.210000] xt_time: kernel timezone is -0000
[   15.220000] usbcore: registered new interface driver ftdi_sio
[   15.230000] usbserial: USB Serial support registered for FTDI USB Serial Device
[   15.400000] nf_tables: (c) 2007-2009 Patrick McHardy <kaber@trash.net>
[   15.440000] PPP generic driver version 2.4.2
[   15.450000] NET: Registered protocol family 24
[   15.470000] usbcore: registered new interface driver option
[   15.480000] usbserial: USB Serial support registered for GSM modem (1-port)
[   26.170000] device eth0 entered promiscuous mode
[   26.220000] br-lan: port 1(eth0) entered forwarding state
[   26.230000] br-lan: port 1(eth0) entered forwarding state
[   26.870000] TX_BCN DESC a69e5000 size = 320
[   26.880000] RX[0] DESC a69e7000 size = 2048
[   26.890000] RX[1] DESC a69e8000 size = 1024
[   26.920000] E2pAccessMode=0
[   26.930000] cfg_mode=10
[   26.930000] cfg_mode=10
[   26.940000] wmode_band_equal(): Band Equal!
[   26.950000] APSDCapable[0]=0
[   26.960000] APSDCapable[1]=0
[   26.960000] APSDCapable[2]=0
[   26.970000] APSDCapable[3]=0
[   26.970000] APSDCapable[4]=0
[   26.980000] APSDCapable[5]=0
[   26.980000] APSDCapable[6]=0
[   26.990000] APSDCapable[7]=0
[   27.000000] APSDCapable[8]=0
[   27.000000] APSDCapable[9]=0
[   27.010000] APSDCapable[10]=0
[   27.010000] APSDCapable[11]=0
[   27.020000] APSDCapable[12]=0
[   27.030000] APSDCapable[13]=0
[   27.030000] APSDCapable[14]=0
[   27.040000] APSDCapable[15]=0
[   27.040000] default ApCliAPSDCapable[0]=0
[   27.050000] default ApCliAPSDCapable[1]=0
[   27.250000] Key1Str is Invalid key length(0) or Type(0)
[   27.260000] Key2Str is Invalid key length(0) or Type(0)
[   27.270000] Key3Str is Invalid key length(0) or Type(0)
[   27.280000] Key4Str is Invalid key length(0) or Type(0)
[   27.350000] RTMPSetDefaultChannel() : default channel to 1
[   27.360000] load fw image from fw_header_image
[   27.370000] AndesMTLoadFwMethod1(2174)::pChipCap->fw_len(63056)
[   27.380000] FW Version:_e2_mp
[   27.390000] FW Build Date:20150211175503
[   27.450000] CmdAddressLenReq:(ret = 0)
[   27.450000] CmdFwStartReq: override = 1, address = 1048576
[   27.460000] CmdStartDLRsp: WiFI FW Download Success
[   27.470000] MtAsicDMASchedulerInit(): DMA Scheduler Mode=0(LMAC)
[   27.490000] efuse_probe: efuse = 10000012
[   27.490000] RtmpChipOpsEepromHook::e2p_type=2, inf_Type=4
[   27.500000] RtmpEepromGetDefault::e2p_dafault=2
[   27.510000] RtmpChipOpsEepromHook: E2P type(2), E2pAccessMode = 2, E2P default = 2
[   27.530000] NVM is FLASH mode
[   27.530000] 1. Phy Mode = 12
[   27.540000] net ra0: Direct firmware load for mt7628.eeprom failed with error -2
[   27.560000] net ra0: Falling back to user helper
[   28.230000] br-lan: port 1(eth0) entered forwarding state
[   28.310000] Country Region from e2p = ffff
[   28.320000] CmdSlotTimeSet:(ret = 0)
[   28.350000] tssi_1_target_pwr_g_band = 35
[   28.350000] 2. Phy Mode = 12
[   28.360000] 3. Phy Mode = 12
[   28.360000] NICInitPwrPinCfg(11): Not support for HIF_MT yet!
[   28.380000] NICInitializeAsic(651): Not support rtmp_mac_sys_reset () for HIF_MT yet!
[   28.390000] mt_mac_init()-->
[   28.400000] MtAsicInitMac()-->
[   28.460000] mt7628_init_mac_cr()-->
[   28.460000] MtAsicSetMacMaxLen(1241): Set the Max RxPktLen=1024!
[   28.470000] <--mt_mac_init()
[   28.480000]  WTBL Segment 1 info:
[   28.490000]          MemBaseAddr/FID:0x28000/0
[   28.490000]          EntrySize/Cnt:32/128
[   28.500000]  WTBL Segment 2 info:
[   28.510000]          MemBaseAddr/FID:0x40000/0
[   28.510000]          EntrySize/Cnt:64/128
[   28.520000]  WTBL Segment 3 info:
[   28.530000]          MemBaseAddr/FID:0x42000/64
[   28.540000]          EntrySize/Cnt:64/128
[   28.540000]  WTBL Segment 4 info:
[   28.550000]          MemBaseAddr/FID:0x44000/128
[   28.560000]          EntrySize/Cnt:32/128
[   28.560000] AntCfgInit(2876): Not support for HIF_MT yet!
[   28.610000] MCS Set = ff 00 00 00 01
[   28.610000] MtAsicSetChBusyStat(826): Not support for HIF_MT yet!
[   32.130000] SYNC - BBP R4 to 20MHz.l
[   33.570000] SYNC - BBP R4 to 20MHz.l
[   33.880000] SYNC - BBP R4 to 20MHz.l
[   34.200000] SYNC - BBP R4 to 20MHz.l
[   34.500000] SYNC - BBP R4 to 20MHz.l
[   34.810000] SYNC - BBP R4 to 20MHz.l
[   35.120000] SYNC - BBP R4 to 20MHz.l
[   35.430000] SYNC - BBP R4 to 20MHz.l
[   35.740000] SYNC - BBP R4 to 20MHz.l
[   36.060000] SYNC - BBP R4 to 20MHz.l
[   36.360000] SYNC - BBP R4 to 20MHz.l
[   36.670000] MtAsicSetRalinkBurstMode(2919): Not support for HIF_MT yet!
[   36.680000] MtAsicSetPiggyBack(763): Not support for HIF_MT yet!
[   36.730000] MtAsicSetTxPreamble(2898): Not support for HIF_MT yet!
[   36.740000] The 4-BSSID mode is enabled, the BSSID byte5 MUST be the multiple of 4
[   36.750000] MtAsicSetPreTbtt(): bss_idx=0, PreTBTT timeout = 0xf0
[   36.760000] Main bssid = 9c:65:f9:1c:16:c1
[   36.770000] <==== rt28xx_init, Status=0
[   36.800000] mt7628_set_ed_cca: TURN OFF EDCCA  mac 0x10618 = 0xd7083f0f
[   36.810000] WiFi Startup Cost (ra0): 9.940s
[   37.530000] MtAsicSetPreTbtt(): bss_idx=0, PreTBTT timeout = 0x0
[   37.540000] MtAsicSetPiggyBack(763): Not support for HIF_MT yet!
[   37.550000] MtAsicSetRalinkBurstMode(2919): Not support for HIF_MT yet!
[   37.570000] MtAsicSetPiggyBack(763): Not support for HIF_MT yet!
[   37.690000] MtAsicSetTxPreamble(2898): Not support for HIF_MT yet!
[   37.700000] AddTxSType: already registered TxSType (PID = 32, Format = 0
[   37.710000] The 4-BSSID mode is enabled, the BSSID byte5 MUST be the multiple of 4
[   37.730000] AddTxSType: already registered TxSType (PID = 6, Format = 0
[   37.740000] MtAsicSetPreTbtt(): bss_idx=0, PreTBTT timeout = 0xf0
[   37.750000] Main bssid = 9c:65:f9:1c:16:c1
[   38.200000] device ra0 entered promiscuous mode
[   38.210000] br-lan: port 2(ra0) entered forwarding state
[   38.220000] br-lan: port 2(ra0) entered forwarding state
[   38.740000] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   38.760000] jffs2_build_filesystem(): unlocking the mtd device... done.
[   38.770000] jffs2_build_filesystem(): erasing all blocks after the end marker...
[   40.220000] br-lan: port 2(ra0) entered forwarding state
[   68.410000] random: nonblocking pool is initialized
[   87.760000] done.
[   87.760000] jffs2: notice: (1687) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
.......

In next step i configure wireless  module as 'sta'  and in console write next messages:

[ 5001.910000] da match,0x9c65f91c16c1
[ 5034.570000] da match,0x9c65f91c16c1
[ 5034.580000] da match,0x9c65f91c16c1
[ 5034.850000] AndesSendCmdMsg: Command type = ed, Extension command type = 27
[ 5034.860000] BUG: AndesSendCmdMsg is called from invalid context
[ 5067.430000] da match,0x9c65f91c16c1
[ 5075.870000] AndesSendCmdMsg: Command type = ed, Extension command type = 27
[ 5075.880000] BUG: AndesSendCmdMsg is called from invalid context
[ 5119.890000] da match,0x9c65f91c16c1
[ 5124.330000] sta_rx_pkt_allow():  No DATA!
[ 5127.890000] AndesSendCmdMsg: Command type = ed, Extension command type = 27
[ 5127.900000] BUG: AndesSendCmdMsg is called from invalid context
[ 5304.370000] sta_rx_pkt_allow():  No DATA!
[ 5364.400000] sta_rx_pkt_allow():  No DATA!
[ 5424.410000] sta_rx_pkt_allow():  No DATA!
[ 5484.430000] sta_rx_pkt_allow():  No DATA!
[ 5544.430000] sta_rx_pkt_allow():  No DATA!
[ 5604.460000] sta_rx_pkt_allow():  No DATA!
[ 5664.470000] sta_rx_pkt_allow():  No DATA!
[ 5724.500000] sta_rx_pkt_allow():  No DATA!
[ 5844.530000] sta_rx_pkt_allow():  No DATA!
[ 5964.560000] sta_rx_pkt_allow():  No DATA!
[ 6024.570000] sta_rx_pkt_allow():  No DATA!
[ 6084.600000] sta_rx_pkt_allow():  No DATA!
[ 6144.610000] sta_rx_pkt_allow():  No DATA!
[ 6204.630000] sta_rx_pkt_allow():  No DATA!
[ 6264.640000] sta_rx_pkt_allow():  No DATA!
[ 6285.160000] da match,0x9c65f91c16c1
[ 6298.910000] AndesSendCmdMsg: Command type = ed, Extension command type = 27
[ 6298.920000] BUG: AndesSendCmdMsg is called from invalid context
[ 6324.660000] sta_rx_pkt_allow():  No DATA!
[ 6384.670000] sta_rx_pkt_allow():  No DATA!
[ 6444.690000] sta_rx_pkt_allow():  No DATA!
[ 6624.800000] sta_rx_pkt_allow():  No DATA!
[ 6684.850000] sta_rx_pkt_allow():  No DATA!
[ 6744.860000] sta_rx_pkt_allow():  No DATA!

....

[16947.490000] sta_rx_pkt_allow():  No DATA!
[17017.930000] AndesSendCmdMsg: Command type = ed, Extension command type = 27
[17017.940000] BUG: AndesSendCmdMsg is called from invalid context
[17020.400000] MtAsicSetPreTbtt(): bss_idx=0, PreTBTT timeout = 0x0
[17020.410000] MtAsicSetPiggyBack(763): Not support for HIF_MT yet!
[17020.420000] MtAsicSetRalinkBurstMode(2919): Not support for HIF_MT yet!
[17020.430000] MtAsicSetPiggyBack(763): Not support for HIF_MT yet!
[17020.470000] MtAsicSetTxPreamble(2898): Not support for HIF_MT yet!
[17020.480000] AddTxSType: already registered TxSType (PID = 32, Format = 0
[17020.500000] The 4-BSSID mode is enabled, the BSSID byte5 MUST be the multiple of 4
[17020.510000] AddTxSType: already registered TxSType (PID = 6, Format = 0
[17020.530000] MtAsicSetPreTbtt(): bss_idx=0, PreTBTT timeout = 0xf0
[17020.540000] Main bssid = 9c:65:f9:1c:16:c1
[17024.450000] AndesSendCmdMsg: Command type = ed, Extension command type = 27
[17024.460000] BUG: AndesSendCmdMsg is called from invalid context
[16887.460000] sta_rx_pkt_allow():  No DATA!

.......

Have any ideas?

**Comment by blogic** [comment]
this should be fixed, please git pull and retest
