### ISSUE TITLE
support smartconfig

### ISSUE THREAD

**Issue by shenghuowang** [MediaTek-Labs/linkit-smart-7688-feed#21]
In Station mode,it is not easy to confg our 7688 connect to a wifi ap,can you support  smartconfig for 7688?

**Comment by blogic** [comment]
2 questions 

*) what is difficult about the config
*) what is smart config

**Comment by PichuChen** [comment]
Hi, smartconfig is a  technology invented by TI, it send ssid and password info by UDP multicast frame.

So the user does not need to disconnect their origin Wi-Fi AP to make the IoT device connect.

**Comment by widora** [comment]
smartconfig is OK on MT76(open source mt7688 wifi driver),which based monitor(sniffer) wifi mode.
But monitor mode is not ok on this bin/ko driver.
