### ISSUE TITLE
if I use mt_wifi.ko_3.18.29_all,I meet the Oops

### ISSUE THREAD

**Issue by widora** [MediaTek-Labs/linkit-smart-7688-feed#22]
code:chaos calmer R49208
the Oops is:
20.810000] br-lan: port 1(eth0) entered forwarding state
[   20.820000] br-lan: port 1(eth0) entered forwarding state
[   21.310000] CPU 0 Unable to handle kernel paging request at virtual address 00000000, epc == 8001ff60, ra == 866e4380
[   21.320000] Oops[#1]:
[   21.320000] CPU: 0 PID: 1120 Comm: ifconfig Not tainted 3.18.29 #2
[   21.320000] task: 8782b548 ti: 86452000 task.ti: 86452000
[   21.320000] $ 0   : 00000000 00000000 00000000 00000f00
[   21.320000] $ 4   : 00000000 00000f00 00000f00 00000002
[   21.320000] $ 8   : 00000020 80008f30 00000060 c05aac18
[   21.320000] $12   : 00000010 60000000 00000000 7fa8dadd
[   21.320000] $16   : 00000001 82000000 c05a5540 c05a553c
[   21.320000] $20   : 00000000 067e8010 00000000 00000000
[   21.320000] $24   : 00000000 8001feb4                  
[   21.320000] $28   : 86452000 86453bf0 c05a5538 866e4380
[   21.320000] Hi    : 00000369
[   21.320000] Lo    : 00001be5
[   21.320000] epc   : 8001ff60 r4k_dma_cache_inv+0xac/0xc8
[   21.320000]     Not tainted
[   21.320000] ra    : 866e4380 linux_pci_map_single+0x68/0x94 [mt_wifi]
[   21.320000] Status: 1100e403 KERNEL EXL IE 
[   21.320000] Cause : 00800008
[   21.320000] BadVA : 00000000
[   21.320000] PrId  : 00019655 (MIPS 24KEc)
[   21.320000] Modules linked in: pppoe ppp_async iptable_nat pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_CT uvcvideo slhc nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat_ftp nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack_ftp nf_conntrack iptable_raw iptable_mangle iptable_filter ip_tables crc_ccitt snd_soc_mt76xx_machine snd_soc_mt76xx_pcm snd_soc_mt76xx_i2s snd_soc_mt76xx_i2s_ctl i2c_wm8960 snd_soc_wm8960 ralink_gdma videobuf2_vmalloc videobuf2_memops videobuf2_core v4l2_common videodev i2c_ralink snd_soc_core mt_wifi i2c_dev ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables snd_compress snd_pcm_oss snd_mixer_oss snd_pcm snd_timer snd_rawmidi snd_seq_device snd_hwdep snd input_core soundcore vfat fat autofs4 nls_utf8 nls_iso8859_1 nls_cp437 regmap_spi regmap_i2c i2c_core regmap_core lzo_decompress lzo_compress ipv6 dma_shared_buffer mmc_block usb_storage sdhci_pltfm sdhci mtk_sd mmc_core leds_gpio ohci_platform ohci_hcd ehci_platform ehci_hcd sd_mod scsi_mod gpio_button_hotplug ext4 jbd2 mbcache exfat drv_regopt usbcore nls_base usb_common crc16 crypto_hash
[   21.320000] Process ifconfig (pid: 1120, threadinfo=86452000, task=8782b548, tls=772b7440)
[   21.320000] Stack : 00000000 c05a553c 00000000 864a8c40 00001000 866e4380 8647dd68 86f604b4
[   21.320000]    86f60480 00000001 c05a3000 86c7fb40 00000f00 866e4458 00000001 00000001
[   21.320000]    8647db00 7fa8d848 0000ff01 034c1313 c05a3000 c05a5520 c05a3000 00000000
[   21.320000]    00000f00 866ae10c 8030a644 8030f004 8030f004 864c9180 c05a553c c05a5540
[   21.320000]    c05a5538 00000080 a0000000 00000000 0000000f 86453d30 c05a3000 86710000
[   21.320000]    ...
[   21.320000] Call Trace:
[   21.320000] [<8001ff60>] r4k_dma_cache_inv+0xac/0xc8
[   21.320000] [<866e4380>] linux_pci_map_single+0x68/0x94 [mt_wifi]
[   21.320000] [<866e4458>] RTMP_AllocateRxPacketBuffer+0xac/0xe0 [mt_wifi]
[   21.320000] [<866ae10c>] RTMPInitTxRxRingMemory+0x4a8/0x600 [mt_wifi]
[   21.320000] [<86654498>] hif_sys_init+0xb4/0x228 [mt_wifi]
[   21.320000] [<86657398>] rt28xx_init+0x9c/0x7ac [mt_wifi]
[   21.320000] [<866e16d8>] rt28xx_open+0xd8/0x398 [mt_wifi]
[   21.320000] [<86671814>] RTMP_COM_IoctlHandle+0x558/0xa7c [mt_wifi]
[   21.320000] [<866e0e58>] MainVirtualIF_open+0x74/0x128 [mt_wifi]
[   21.320000] [<801e79a0>] __dev_open+0xe0/0x148
[   21.320000] [<801e7c90>] __dev_change_flags+0xb8/0x170
[   21.320000] [<801e7d70>] dev_change_flags+0x28/0x70
[   21.320000] [<80245530>] devinet_ioctl+0x63c/0x674
[   21.320000] [<801cfb34>] sock_ioctl+0x2b0/0x30c
[   21.320000] [<800b0038>] do_vfs_ioctl+0x4d4/0x5e0
[   21.320000] [<800b0194>] SyS_ioctl+0x50/0x94
[   21.320000] [<80006b5c>] handle_sys+0x11c/0x140
[   21.320000] 
[   21.320000] 
[   21.320000] Code: 2484ffff  00852821  00a31824 <bc510000> 1443fffe  24420020  0000000f  8fbf0014  03e00008 
[   21.690000] rt305x-esw 10110000.esw: link changed 0x01
[   21.690000] ---[ end trace 517eff51a1c04bf5 ]---
[   22.820000] br-lan: port 1(eth0) entered forwarding state

I want know how to mt_wifi.ko_3.18.29_all module，thx，：）

**Comment by blogic** [comment]
did you build your kernel with all kmods enabled or did you manually select this module ?

**Comment by widora** [comment]
Kernel configuration I have not changed

**Comment by widora** [comment]
Be sure to select the kernel of all kmods?

**Comment by blogic** [comment]
look at line 84

https://github.com/MediaTek-Labs/linkit-smart-7688-feed/blob/master/mtk-sdk-wifi/Makefile#L84

**Comment by widora** [comment]
thank you，I doing test :)
