### ISSUE TITLE
Wifi does not detect router which is in auto channel

### ISSUE THREAD

**Issue by bapclenet** [MediaTek-Labs/linkit-smart-7688-feed#24]
The router is in DHCP mode auto-channel.
The wifi driver of linkit does not detect the router every time.
This does not seem to appear with fixed channel.
Is this behaviour a known issue?

**Comment by blogic** [comment]
your AP is on channel 12/13 which is not supported by the 0.9.3 release. 0.9.4 will have handling for this.

**Comment by biboc** [comment]
Is 0.9.4 released and where do I see driver version?

**Comment by biboc** [comment]
PING?

Is new driver released?
