### ISSUE TITLE
About mt_wifi.ko_3.18.36 No such file or directory

### ISSUE THREAD

**Issue by danielb987** [MediaTek-Labs/linkit-smart-7688-feed#25]
I'm trying to build openwrt for Linkit Smart 7688 Duo and I get the error that mt_wifi.ko_3.18.36 is missing. And I realize that I have the same error as this: https://github.com/MediaTek-Labs/linkit-smart-7688-feed/issues/17

I looked at the GIT repository and found that CC had a kernel update from 3.18 to 3.18.36 two days ago and that explains why I cannot build. So a new build of the mt_wifi.ko module is needed.

Kind regards,
Daniel

**Comment by blogic** [comment]
the kernel got updated inside CC last week, i'll push the new binaries start of the week.

**Comment by danielb987** [comment]
Thanks.

**Comment by ladams00** [comment]
I second this issue.

**Comment by blogic** [comment]
I have just pushed an update.
