### ISSUE TITLE
[Question] check if wifi connected

### ISSUE THREAD

**Issue by bapclenet** [MediaTek-Labs/linkit-smart-7688-feed#26]
Hi,

I set the configuration of 7688 to connect wifi to another router (B). How can I check that the board is really connected to B? (from CLI)
I know the board is connected because I see it on B dashboard but I need to know from the board.

Also, it is very slow to connect to another router (around 20secs), is it normal?

Cheers,

**Comment by bapclenet** [comment]
PING

**Comment by blogic** [comment]
there is currently no way to tell via cli and 20s is the timeout of the cli tool to verify if the station assoced.

**Comment by bapclenet** [comment]
Thanks for your answer.
Is there another way then? Is it planned to add it in the next release?

**Comment by blogic** [comment]
you can very easily modify the ap_client tool to add this feature. when you have a patch ready post it please so others can use it aswell

**Comment by bapclenet** [comment]
I see, I need to use this command: iwpriv apcli0 show connStatus ? So I need to edit the iwpriv function in ap_client.
Thing is the output goes not on terminal, it goes to some logs and I don't see how to get them from ap_client, any idea?

**Comment by blogic** [comment]
as i replied earlier, the easiest way is to patch ap_client.c

**Comment by bapclenet** [comment]
Yes I know, I'll ad a command to ap_client to call this function because IMO "show connStatus" is the only way to check if ap_client is connected, right?
I'll try but I'm afraid that I won't get the output when I'll call the ioctl, don't you think?

**Comment by bapclenet** [comment]
Ok check_assoc may be much easier
