### ISSUE TITLE
SET failed on device ra0 ; Operation not supported.

### ISSUE THREAD

**Issue by ferren** [MediaTek-Labs/linkit-smart-7688-feed#28]
I want to set mt7688 to monitor mode use the command below, and got a error.
-------------------------------------------------
root@mylinkit:/# iwconfig ra0 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device ra0 ; Operation not supported.
-------------------------------------------------

How can I make mt_wifi.ko to support SIOCGIWMODE operation?

**Comment by blogic** [comment]
he SDK wifi driver does not support monitor mode.

**Comment by ferren** [comment]
My application need that wifi driver ( with monitor mode). 
Who can give me some help, or give me some hints. Thanks!

**Comment by blogic** [comment]
there will be a new release soon with monitor mode.

**Comment by widora** [comment]
@ferren 
iwpriv ra0 elian monitor_on
iwpriv ra0 elian monitor_off
is OK on my wifi driver.

**Comment by memand** [comment]
@blogic 
Sorry for necro post but do you have any news on thi new driver?

**Comment by blogic** [comment]
i am not working on this anymore. please contact the product manager -> VincentSH Hsu (徐士璿) <vincentsh.hsu@mediatek.com>

**Comment by lcotonea** [comment]
This a a real necro post (4 years later) :) Do you have any news on this driver with monitor mode support?
