### ISSUE TITLE
mt_wifi.ko_3.18.44': No such file or directory

### ISSUE THREAD

**Issue by garylijs** [MediaTek-Labs/linkit-smart-7688-feed#32]
Hi,
I try to compile OpenWRT mt7688 fireware by MediaTek_LinkIt_Smart_7688_Developers_Guide_V1.1.pdf 7.1;

cp -fpR /home/gary/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ap_client /home/gary/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/sbin/
cp -fpR ./wifi_binary/mt_wifi.ko_3.18.44 /home/gary/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/lib/modules/3.18.44/mt_wifi.ko
cp: cannot stat './wifi_binary/mt_wifi.ko_3.18.44': No such file or directory
Makefile:93: recipe for target '/home/gary/openwrt/bin/ramips/packages/linkit/mtk-sdk-wifi_2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371_ramips_24kec.ipk' failed
make[3]: *** [/home/gary/openwrt/bin/ramips/packages/linkit/mtk-sdk-wifi_2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371_ramips_24kec.ipk] Error 1
make[3]: Leaving directory '/home/gary/openwrt/feeds/linkit/mtk-sdk-wifi'
package/Makefile:191: recipe for target 'package/feeds/linkit/mtk-sdk-wifi/compile' failed
make[2]: *** [package/feeds/linkit/mtk-sdk-wifi/compile] Error 2
make[2]: Leaving directory '/home/gary/openwrt'
package/Makefile:188: recipe for target '/home/gary/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/gary/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gary/openwrt'
/home/gary/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2

How to solve it?

Thanks, Gary

**Comment by Pillar1989** [comment]
Maybe you can back to openwrt: ba4b52c8e145526c396a619af19a5deb42a6cbfb

**Comment by garylijs** [comment]
@Pillar1989 How to back to......., do you have any steps? tks.

**Comment by Pillar1989** [comment]
```sh
git clone https://github.com/openwrt/
cd openwrt
git checkout ba4b52c8e145526c396a619af19a5deb42a6cbfb -b fuck_freshman
```

**Comment by garylijs** [comment]
@Pillar1989 Thanks so much, I will try it again.

**Comment by garylijs** [comment]
@Pillar1989 If I could go back to last version (kernel version is 3.18.36) by you list steps?

**Comment by Pillar1989** [comment]
```sh
git log | grep  3.18.36
```
You will find kernel 3.18.23 commits.

**Comment by garylijs** [comment]
@Pillar1989 oh...I wish to download openwrt is 15.05 version. How to go back to 15.05, and based on kernel 3.18.36.

**Comment by Pillar1989** [comment]
```sh
git clone https://github.com/openwrt/ -b chaos_calmer
cd openwrt
git log | grep  3.18.36
git checkout any_commit -b fuck_freshman
```

**Comment by garylijs** [comment]
@Pillar1989 I met follow issue, how to solve it?
$git clone https://github.com/openwrt/ -b chaos_calmer
Cloning into 'openwrt'...
fatal: repository 'https://github.com/openwrt/' not found

**Comment by Pillar1989** [comment]
```sh
git clone https://github.com/openwrt/openwrt
```

**Comment by garylijs** [comment]
@Pillar1989 cheer....,, thanks, downloading is fine.

**Comment by garylijs** [comment]
@Pillar1989 I got follow message according to your steps, I don't know if it's OK to get openwrt 15.05 with kernel version is 3.18.36 by MediaTek_LinkIt_Smart_7688_Developers_Guide_V1.1.pdf 7.1;
Please help me to double confirm it, thanks so..


gary@gary-VirtualBox:~$ cd openwrt/
gary@gary-VirtualBox:~/openwrt$ git log | grep 3.18.36
    CC: kernel: update kernel 3.18 to version 3.18.36
Date:   Mon Jul 15 23:18:36 2013 +0000
commit 32a46a58384436cee3b18b3621693903872b86f5
gary@gary-VirtualBox:~/openwrt$ git checkout 32a46a58384436cee3b18b3621693903872b86f5 -b fuck_freshman
Switched to a new branch 'fuck_freshman'
gary@gary-VirtualBox:~/openwrt$

**Comment by garylijs** [comment]
@Pillar1989 'git checkout any_commit -b fuck_freshman', what are any_commit and fuck_freshman?
gary@gary-VirtualBox:~/openwrt$ git log | grep 3.18.36
    CC: kernel: update kernel 3.18 to version 3.18.36
Date:   Mon Jul 15 23:18:36 2013 +0000
commit 32a46a58384436cee3b18b3621693903872b86f5
gary@gary-VirtualBox:~/openwrt$ git checkout 32a46a58384436cee3b18b3621693903872b86f5 -b xxxxxx

**Comment by garylijs** [comment]
Above steps completed, what to do next?

**Comment by garylijs** [comment]
@Pillar1989 Tks, I can go back to openwrt 15.05 with kernel is 3.18.36
