### ISSUE TITLE
Compile failed with the latest openwrt 15.05 branch

### ISSUE THREAD

**Issue by AgingChan** [MediaTek-Labs/linkit-smart-7688-feed#34]
The openwrt 15.05 has updated the kernel version to 3.18.44 which will result in the compilation failure of the mtk-sdk-wifi due to the lack of file wifi_binary/mt_wifi.ko_3.18.44  and ./wifi_binary/mt_wifi.ko_3.18.44_all.

Here is the compilation error:
cp -fpR ./wifi_binary/mt_wifi.ko_3.18.44 /myspace/jbtgw/repos/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mtk-sdk-wifi-2015-06-01/ipkg-ramips_24kec/mtk-sdk-wifi/lib/modules/3.18.44/mt_wifi.ko
cp: cannot stat './wifi_binary/mt_wifi.ko_3.18.44': No such file or directory
Makefile:93: recipe for target '/myspace/jbtgw/repos/openwrt/bin/ramips/packages/jbtgw/mtk-sdk-wifi_2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371_ramips_24kec.ipk' failed

**Comment by netros** [comment]
same issue

**Comment by guanch1984** [comment]
Is there way to roll back to 3.18.36 ?

**Comment by AgingChan** [comment]
Hi There, 

To workaround, you could just rename the following two files
    mt_wifi.ko_3.18.36_all ---> mt_wifi.ko_3.18.44_all 
    mt_wifi.ko_3.18.36 ---> mt_wifi.ko_3.18.44 
This can make the compile pass.

**Comment by hex4def6** [comment]
Isn't version magic going to prevent that from working?

**Comment by guanch1984** [comment]
renamed it, got it working for now.

**Comment by blogic** [comment]
pushed the missing files

**Comment by abard** [comment]
Thank you very much @blogic for the updated driver,
Any news about the open source driver? I really need the mesh functions (802.11s).
Do you know you by chance what standard does the ad-hoc mode in the SDK  holds?
