### ISSUE TITLE
Is there a ATmega32U4 firmware could let DUO work with Breadkboard Seeed SKU SKU 103100022

### ISSUE THREAD

**Issue by guanch1984** [MediaTek-Labs/linkit-smart-7688-feed#38]
Here is the DUO board link 
https://www.seeedstudio.com/LinkIt-Smart-7688-Duo-p-2574.html

Here is breakboard link
https://www.seeedstudio.com/Breakout-for-LinkIt-Smart-7688-v2.0-p-2641.html

**Comment by shihhsuan** [comment]
No. The breakout board is for the LinkIt Smart 7688, not for the LinkIt Smart 7688 DUo. These two boards are with incompatible pin out and cannot be used interchangeable.
