### ISSUE TITLE
can i build openwrt-19 with this feed?

### ISSUE THREAD

**Issue by hitfzyangdianshi** [MediaTek-Labs/linkit-smart-7688-feed#53]
can i build openwrt-19 with this feed?
i want to use openwrt19 not 15 with linkit smart 7688

**Comment by JontyC** [comment]
@hitfzyangdianshi Did you disable Wi-Fi to get this working on 19.x?

**Comment by hitfzyangdianshi** [comment]
I do not use this feed anymore. I use openwrt19 directly, from https://github.com/openwrt/openwrt
