### ISSUE TITLE
fatal: No tags can describe 'e6fbf31baae41b618ff333f3ae55ff032333bd6a'. Try --always, or create some tags.

### ISSUE THREAD

**Issue by hitfzyangdianshi** [MediaTek-Labs/linkit-smart-7688-feed#54]
Create index file './feeds/luci.index' 
fatal: No tags can describe 'e6fbf31baae41b618ff333f3ae55ff032333bd6a'.
Try --always, or create some tags.
fatal: No tags can describe 'e6fbf31baae41b618ff333f3ae55ff032333bd6a'.
Try --always, or create some tags.
fatal: No tags can describe 'e6fbf31baae41b618ff333f3ae55ff032333bd6a'.
Try --always, or create some tags.
Collecting package info: done
fatal: No tags can describe 'e6fbf31baae41b618ff333f3ae55ff032333bd6a'.
Try --always, or create some tags.
Collecting target info: done

**Comment by JontyC** [comment]
@hitfzyangdianshi Did you manage to resolve this? Having the same issue.

**Comment by hitfzyangdianshi** [comment]
> @hitfzyangdianshi Did you manage to resolve this? Having the same issue.

no. I have given up to use this version, and I use the latest Openwrt 19 firmware now.

**Comment by hitfzyangdianshi** [comment]
try to use the previous commit 53c70521a69e303a01387746dd45297dab48a0d7
