### ISSUE TITLE
Error 404: Not found issue

### ISSUE THREAD

**Issue by versamodule** [MediaTek-Labs/linkit-smart-7688-feed#6]
Linux Version: 4.2.0-22-generic
Linux Dist: Ubuntu 15.10 & 14.04.3 LTS

I have tried these instructions on 2 different computer, both with same results. 
Each computer was a new install of Ubuntu, and all updates/upgrades applied, nothing else installed. 
Then jumped right into the instructions here. 

Made no changed to menuconfig other than the 3 noted to change. 
after the make & 5 hours later I get the following on both computers. 

make[3]: Leaving directory '/home/jim/openwrt/package/network/utils/curl'
make[3]: Entering directory '/home/jim/openwrt/package/system/ca-certificates'
mkdir -p /home/jim/openwrt/dl
/home/jim/openwrt/scripts/download.pl "/home/jim/openwrt/dl" "ca-certificates_20150426.tar.xz" "717455f13fb31fd014a11a468ea3895d" "http://ftp.debian.org/debian/pool/main/c/ca-certificates"
--2015-12-30 14:51:42--  http://ftp.debian.org/debian/pool/main/c/ca-certificates/ca-certificates_20150426.tar.xz
Resolving ftp.debian.org (ftp.debian.org)... 130.89.148.12, 2001:610:1908:b000::148:12
Connecting to ftp.debian.org (ftp.debian.org)|130.89.148.12|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-30 14:51:42 ERROR 404: Not Found.

Download failed.
--2015-12-30 14:51:42--  http://mirror2.openwrt.org/sources/ca-certificates_20150426.tar.xz
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 46.4.11.11
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|46.4.11.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-30 14:51:43 ERROR 404: Not Found.

Download failed.
--2015-12-30 14:51:43--  http://downloads.openwrt.org/sources/ca-certificates_20150426.tar.xz
Resolving downloads.openwrt.org (downloads.openwrt.org)... 78.24.191.177
Connecting to downloads.openwrt.org (downloads.openwrt.org)|78.24.191.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-30 14:51:45 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
Makefile:47: recipe for target '/home/jim/openwrt/dl/ca-certificates_20150426.tar.xz' failed
make[3]: *** [/home/jim/openwrt/dl/ca-certificates_20150426.tar.xz] Error 2
make[3]: Leaving directory '/home/jim/openwrt/package/system/ca-certificates'
package/Makefile:191: recipe for target 'package/system/ca-certificates/compile' failed
make[2]: *** [package/system/ca-certificates/compile] Error 2
make[2]: Leaving directory '/home/jim/openwrt'
package/Makefile:188: recipe for target '/home/jim/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/jim/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jim/openwrt'
/home/jim/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2
jim@jim-HP-2000-Notebook-PC:~/openwrt$

**Comment by auronc** [comment]
I've the same issue.

**Comment by auronc** [comment]
I pass the problem:
cd <PATH_TO>/openwrt
wget https://launchpad.net/ubuntu/+archive/primary/+files/ca-certificates_20150426.tar.xz -P ./dl/
make V=99

**Comment by blogic** [comment]
file was just copied to the openwrt mirror server
