### ISSUE TITLE
Make issue, pkgconfig.freedesktop.org

### ISSUE THREAD

**Issue by versamodule** [MediaTek-Labs/linkit-smart-7688-feed#9]
I have done the steps to compile several times before with success. Today I tried it again and received this error. Below is a clip of the last part of the output. 

make[3]: Entering directory `/home/jim/openwrt/tools/pkg-config'
mkdir -p /home/jim/openwrt/dl
/home/jim/openwrt/scripts/download.pl "/home/jim/openwrt/dl" "pkg-config-0.29.tar.gz" "77f27dce7ef88d0634d0d6f90e03a77f" "http://pkgconfig.freedesktop.org/releases/"
--2016-02-07 09:38:38--  http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz
Resolving pkgconfig.freedesktop.org (pkgconfig.freedesktop.org)... 131.252.210.176
Connecting to pkgconfig.freedesktop.org (pkgconfig.freedesktop.org)|131.252.210.176|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz [following]
--2016-02-07 09:38:38--  https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz
Connecting to pkgconfig.freedesktop.org (pkgconfig.freedesktop.org)|131.252.210.176|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-07 09:38:39 ERROR 404: Not Found.

Download failed.
--2016-02-07 09:38:39--  http://mirror2.openwrt.org/sources/pkg-config-0.29.tar.gz
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 46.4.11.11
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|46.4.11.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-07 09:38:39 ERROR 404: Not Found.

Download failed.
--2016-02-07 09:38:39--  http://downloads.openwrt.org/sources/pkg-config-0.29.tar.gz
Resolving downloads.openwrt.org (downloads.openwrt.org)... 78.24.191.177
Connecting to downloads.openwrt.org (downloads.openwrt.org)|78.24.191.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-07 09:38:39 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
make[3]: *** [/home/jim/openwrt/dl/pkg-config-0.29.tar.gz] Error 2
make[3]: Leaving directory `/home/jim/openwrt/tools/pkg-config'
make[2]: *** [tools/pkg-config/compile] Error 2
make[2]: Leaving directory `/home/jim/openwrt'
make[1]: *** [/home/jim/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.tools_install_yynyynynynyyyyyyyyynyyyyyyyyynyyyyynnyyynnyynnnyy] Error 2
make[1]: Leaving directory `/home/jim/openwrt'
make: *** [world] Error 2
jim@ubuntu:~/openwrt$ ^C
jim@ubuntu:~/openwrt$

**Comment by blogic** [comment]
File has been uploaded to the openwrt mirror. please retry.

**Comment by krispstack** [comment]
Still the same issue

>  Applying ./patches/100-aclocal-skip-not-existing-directories.patch using plaintext: 
patching file bin/aclocal.in

Applying ./patches/200-do-not-override-silent-rules.patch using plaintext: 
patching file m4/silent.m4
touch /home/karthi/chaos_calmer/build_dir/host/automake-1.15/.prepared39a010ae98078b627fd56aefee27c46c
(cd /home/karthi/chaos_calmer/build_dir/host/automake-1.15; AUTOM4TE=/home/karthi/chaos_calmer/staging_dir/host/bin/autom4te AUTOCONF=/home/karthi/chaos_calmer/staging_dir/host/bin/autoconf AUTOMAKE=/home/karthi/chaos_calmer/staging_dir/host/bin/automake ACLOCAL=/home/karthi/chaos_calmer/staging_dir/host/bin/aclocal AUTOHEADER=/home/karthi/chaos_calmer/staging_dir/host/bin/autoheader LIBTOOLIZE=/home/karthi/chaos_calmer/staging_dir/host/bin/libtoolize LIBTOOL=/home/karthi/chaos_calmer/staging_dir/host/bin/libtool M4=/home/karthi/chaos_calmer/staging_dir/host/bin/m4 AUTOPOINT=true STAGING_DIR="" ./bootstrap.sh)
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at ./bin/automake.tmp line 3938.
Makefile:50: recipe for target '/home/karthi/chaos_calmer/build_dir/host/automake-1.15/.configured' failed
make[3]: *** [/home/karthi/chaos_calmer/build_dir/host/automake-1.15/.configured] Error 255
make[3]: Leaving directory '/home/karthi/chaos_calmer/tools/automake'
tools/Makefile:122: recipe for target 'tools/automake/compile' failed
make[2]: *** [tools/automake/compile] Error 2
make[2]: Leaving directory '/home/karthi/chaos_calmer'
tools/Makefile:121: recipe for target '/home/karthi/chaos_calmer/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.tools_install_yynyynynynyyyyyyyyynyyyyyyyyynyyyyynnyyynnyynnnyy' failed
make[1]: *** [/home/karthi/chaos_calmer/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.tools_install_yynyynynynyyyyyyyyynyyyyyyyyynyyyyynnyyynnyynnnyy] Error 2
make[1]: Leaving directory '/home/karthi/chaos_calmer'
/home/karthi/chaos_calmer/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2
